CREATE TABLE IF NOT EXISTS weight_logs (
  id INT8 GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  date DATE DEFAULT CURRENT_DATE,
  weight INT DEFAULT 0
);

ALTER TABLE IF EXISTS public.weight_logs DISABLE ROW LEVEL SECURITY;
